spin_manifest_version = 2

[application]
name = "chrismatteson-com-website"
version = "0.1.0"
authors = ["Chris Matteson <chris.matteson@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "chrismatteson-com-website"

[component.chrismatteson-com-website]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "dist", destination = "/" }]

[[trigger.http]]
route = "/images/..."
component = "chrismatteson-com-website-images"

[component.chrismatteson-com-website-images]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "public/images", destination = "/" }]
